### PR TITLE
feat: add the ability to configure `Http` values

### PR DESCRIPTION
**Pull request by yusdacra**
This PR adds a new trait to allow the created `Http` to be configured.

### CODE REVIEW

**Comment by yusdacra** [comment]
I don't know about the inner workings of `hyper`, but if `.clone()`-ing an `Http` is fine I can change it to do that (wasn't sure if it would cause problems or not).

**Comment by programatik29** [comment]
It shouldn't cause problems but `hyper` API may change in the future, we should create a new type that holds configuration values and allow it to be passed to `Server`.

**Comment by programatik29** [comment]
This new type can wrap `hyper::server::conn::Http` to make things easier.

**Comment by yusdacra** [comment]
OK, implemented a new struct for it then. Please take a look :slightly_smiling_face: I think it's only missing the `http1_writeev` method, it doesn't seem to be enabled with the current features `axum-server` has enabled so it should be fine (?). And the struct doesn't allow setting `Exec`, also need to add that.

**Comment by programatik29** [comment]
Looks good.

`http1_writev` method is not present on `0.14.14` version. Also there is no need to allow setting `Exec` since we are only supporting `tokio` (by setting `hyper/runtime` feature).

**Comment by yusdacra** [comment]
Oh, I see. If it's good then that's nice :slightly_smiling_face: I need this feature for a crate of mine so would appreciate if a minor release could be made for it.

**Comment by programatik29** [comment]
I will work on this tomorrow, probably release `0.3.1` in few days.

**Pull request merged**
